#!/usr/bin/env python


import re
import glob

import numpy as np
import matplotlib.pyplot as plt


def plot_individual_lengths(data, ax):
  for file in data_files:
    with open(file, 'r') as f:
        for line in f:
          # Exclude whitespace-only lines
          if not re.search("\A\s\Z", line):
            data.append(len(line))

    data.sort(reverse=True)
    ax.plot(data, '.')
    data = []

def plot_total_lengths(data, ax):
  for file in data_files:
    with open(file, 'r') as f:
      for line in f:
        # Exclude whitespace-only lines
        if not re.search("\A\s\Z", line):
          data.append(len(line))

  data.sort(reverse=True)
  ax.plot(data, '.')
  data = []

def plot_history():
  fig = plt.figure()
  ax = fig.add_subplot(111)

  # Plot the individual lengths:
  # plot_individual_lengths(data, ax)
  
  # Plot the total lengths:
  plot_total_lengths(data, ax)

  #
  #
  # Any further analysis function goes here (taking the data and the axis
  # as arguments):
  #
  #

  plt.show()


if __name__ == '__main__':
  data_dir = './data/githubHistoryFiles/'
  data = []
  BAR_WIDTH = 3
  data_files = glob.glob(data_dir + '*')

  plot_history()
