ls
cd
ls
ssh -T -i ~/.ssh/id_rsa git@github.com
ssh-keygen 
git remote add origin https://github.com/cmdcollab/RB.git
rm -rf .git
git remote add origin https://github.com/cmdcollab/RB.git
git remote add origin ssh://github.com/cmdcollab/RB.git
git remote add origin https://github.com/cmdcollab/RB.git
git remote add origin git@github.com:cmdcollab/RB.git
git push -u origin master
git init
git remote add origin git@github.com:cmdcollab/RB.git
git push -u origin master
cat ~/.ssh/id_rsa
cat ~/.ssh/id_rsa.pub 
cp -ax /var/www/rubybox.cmdhosting.co.za/web/* .
exit
