git push origin develop
..
cd frontend/
npm start
..
cd api/
gma "updating cors"
git push origin develop
npm start
..
cd frontend/
ll
npm start
..
cd api/
npm start
cd ../frontend/
npm start
mongo
..
cd api/
npm start
npm stop
npm start
mongo
npm stop
npm start
npm stop
npm start
mongo
npm stop
npm start
npm stop
node app/lib/rebelclef.js 
npm start
..
cd frontend/
ll
npm start
..
cd api/
ll
npm stop
ll
git add .
gma "updating api to valiate properly, and to use label value instead of title"
git push origin develop
gb
..
git push origin develop
git pull origin develop
cd api/
ll
git push origin develop
..
cd frontend/
ll
git pull origin develop
gma "cleanup"
git pull origin develop
git status
gma "fixing conflicts"
git push origin develop
git pull origin develop
git push origin develop
gb
git flow init
gb
git push origin develop
npm start
..
cd api/
npm start
..
cd frontend/
ll
npm start
..
cd api/
ll
npm start
exit
jsdev
sk
cb this is a test
pbcopy -help
pbcopy test
xclip -help
echo hello | pbcopy
sk
cb test
sk
li
sk
cb test
sk
jspwd
jsprod
devjs
rm -rf mers/
ll
devjs
cd mers/
npm test
git clone git://github.com/jspears/mers.git
cd mers
npm install
NODE_ENV=development node example/app.js
ll
NODE_ENV=development node example/app.js
..
rm -rf mers/
ll
git clone https://github.com/meshachjackson/mers.git
ll
cd mers/
ll
npm install
ll
node example/app.js 
cd example/
ll
npm install
node app.js 
NODE_ENV=development node app.js
ll
..
ll
cd mers/
ll
git add .
gma "adding modules"
ll
git push origin master
ll
cd node_modules/
ll
git clone git://github.com/powmedia/mongoose-fixtures.git
ll
cd mongoose-fixtures/
ll
rm -rf .git/
ll
..
ll
..
npm start
ll
nano package.json 
npm test
nano package.json 
npm start
ll
nano package.json 
npm start
mongo
sk
ssh -p 2200 mjackson@quickish.com
jsprod
sk
flushdns
devjs
..
cd client/
ll
cd quickish/
ll
..
mkdir quickish_aws
cd quickish_aws/
clone git@github.com:usatoday-smb/quickish.git
git clone git@github.com:usatoday-smb/quickish.git
git clone https://github.com/usatoday-smb/quickish.git
ll
cd quickish/
ll
nano README.md 
git add .
gma "initial commit"
git push origin master
qprod
qdev
sk
ssh -P 2200 mjackson@quickish.com
ssh -p 2200 mjackson@quickish.com
ll
..
git clone git@codebasehq.com:jollyscience/quickish/quickish.git
ll
mv quickish/ usat_quickish
ll
git clone git@codebasehq.com:jollyscience/quickish/quickish.git
ll
cd usat_quickish/
ll
..
cd quickish/
ll
..
cp -r quickish/app/* usat_quickish/app/
ll
cd usat_quickish/
ll
cd app/
ll
..
ll
..
ll
cp -r quickish/cake/* usat_quickish/cake/*
ll
cd quickish/cake/
ll
..
ll
..
cp -r quickish/docroot/* usat_quickish/docroot/*
cp -r quickish/docroot/* usat_quickish/docroot/
cp -r quickish/docroot/* usat_quickish/docroot
cp -R quickish/docroot/* usat_quickish/docroot
cp -r quickish/docroot/ usat_quickish/
ll
cd usat_quickish/
ll
..
rm -rf usat_quickish/
ll
cd quickish/
ll
rm -rf .git
rm -rg .gitmodules 
rm -rf .gitmodules 
ll
git init
git add .
gma "initial commit"
ll
nano README.md
ll
git remote add origin https://github.com/usatoday-smb/quickish.git
git push origin master
git pull origin master
ll
rm -rf .git/*
ll
rm -rf .git/*
ll
rm -rg .git/
ll
rm -rf .git/
ll
git remote add origin https://github.com/jollyscience/quickish.git
ll
git init
git add .
gma "initial commit"
git remote add origin https://github.com/jollyscience/quickish.git
git pull origin master
ll
nano README.md 
gma "cleanup"
git pull origin master
git push origin master
ll
git pull origin master
ll
cd cake/
ll
wget https://github.com/cakephp/cakephp/zipball/1.3
ll
unzip 1.3 
ll
rm -rf 1.3 
ll
cd cakephp-cakephp-3d8f090/
ll
rm -rf app/
ll
..
ll
cp -r cakephp-cakephp-3d8f090/* ./
ll
rm -rf cakephp-cakephp-3d8f090/
ll
..
ll
cd cake/
ll
..
ll
..
ll
cp -r quickish/* ./
ll
rm -rf quickish/
ll
..
ll
cd quickish
ll
cd cake/
ll
cd cake/
ll
..
ll
..
cp -r cake/ ../quickish_aws/
cd ../quickish_aws/cake/
ll
..
ll
rm -rf cake/
ll
git reset --HARD HEAD
git reset --hard HEAD
ll
rm -rf README
ll
cd cake/
ll
..
ll
.
..
rm -rf quickish_aws/
ll
git clone https://github.com/jollyscience/quickish.git
mv quickish/ quickish_linode
git clone https://github.com/jollyscience/quickish.git
ll
cd quickish
ll
cp -r ../quickish_linode/cake/ ./cake
ll
cd cake/
ll
..
ll
git add .
gma "adding cake"
git push origin master
ll
cd cake/
ll
rm -rf .git*
ll
..
git add .
gma "adding cake"
git push origin master
ll
cd cake/
ll
..
ll
cd cake/
ll
cd cake/
ll
..
ll
..
ll
git add .
gma "cleanup"
gb
git push origin master
git pull origin master
git rm -r --cached
git rm -r --cached .
ll
git push origin master
git rm -r --cached .
git pull origin master
gma "cleanup"
git push origin master
ll
git pull origin master
git add .
gma "cleanup"
git push origin master
cat ~/.ssh/id_rsa.pub
sk
getssh
git pull origin master
git push origin master
ll
git add .
gma "adding db dump"
git push origin master
ll
exit
npm install jitsu -g
jitsu users confirm jollyscience b14d1830-da09-46f2-839f-bbcb8710e8e1
devjs
mkdir myapp
cd myapp/
ll
nano server.js
ll
jitsu
jitsu deploy
ll
jitsu create
ll
jitsu login
jitsu apps
jitsu apps list
jitsu install
ll
jitsu deploy helloworld
cd helloworld/
jitsu deploy
ll
nano bin/server
jitsu deploy
exit
sk
flushdns
jsdev
ping topps.jollyscience.com
flushdns
ping topps.jollyscience.com
flushdns
ping topps.jollyscience.com
flushdns
ping topps.jollyscience.com
flushdns
ping topps.jollyscience.com
flushdns
ping topps.jollyscience.com
ping dev01.jollyscience.com
exit
flushdns
ping dev.topps.jollyscience.com
jsdev
devjs
..
ll
cd misc/
ll
git clone https://github.com/h5bp/html5-boilerplate.git
ll
mv html5-boilerplate/ meshachjacksondotcom
ll
cd meshachjacksondotcom/
ll
..
git clone git://github.com/twitter/bootstrap.git
jsdev
jsprod
sk
jspwd
jsprod
jspwd
sk
ssh -p 2200 mjackson@quickish.com
sk
$ ssh -i path/to/keypair.pub ec2-user@ec2-an-ip-address.compute-1.amazonaws.com
$ ssh -i /Users/mjackson/Downloads/quickish.pem meshach@ec2-23-22-15-180.compute-1.amazonaws.com
ssh -i /Users/mjackson/Downloads/quickish.pem meshach@ec2-23-22-15-180.compute-1.amazonaws.com
mv /Users/mjackson/Downloads/quickish.pem /Users/mjackson/cita/client/quickish-aws/
mv /Users/mjackson/Downloads/quickish.pem /Users/mjackson/cita/client/quickish-aws/quickish.pem
mkdir /Users/mjackson/cita/client/quickish-aws
mv /Users/mjackson/Downloads/quickish.pem /Users/mjackson/cita/client/quickish-aws/quickish.pem
chmod 400 ~/cita/client/quickish-aws/quickish.pem
ssh -i /Users/mjackson/cita/client/quickish-aws/quickish.pem meshach@ec2-23-22-15-180.compute-1.amazonaws.com
ssh -i /Users/mjackson/cita/client/quickish-aws/quickish.pem i-d128adaa@ec2-23-22-15-180.compute-1.amazonaws.com
ssh -i /Users/mjackson/cita/client/quickish-aws/quickish.pem meshach@ec2-23-22-15-180.compute-1.amazonaws.com
chmod 0400 ~/cita/client/quickish-aws/quickish.pem
ssh -i /Users/mjackson/cita/client/quickish-aws/quickish.pem meshach@ec2-23-22-15-180.compute-1.amazonaws.com
devjs
..
cd client/
ll
cd quickish-aws/
ll
git clone https://github.com/usatoday-smb/quickish.git
ssh -i /Users/mjackson/cita/client/quickish-aws/quickish.pem ec2-user@ec2-23-22-15-180.compute-1.amazonaws.com
devjs
..
cd client/quickish-aws/
ll
cd quickish/
ll
git aws.config
sh /Users/mjackson/Downloads/AWS-ElasticBeanstalk-CLI-2.0/AWSDevTools/Linux/AWSDevTools-RepositorySetup.sh 
git aws.config
git aws.push
curl -L https://get.rvm.io | bash -s stable --ruby
curl -k -L https://get.rvm.io | bash -s stable --ruby
echo insecure >> ~/.curlrc
curl -k -L https://get.rvm.io | bash -s stable --ruby
source /Users/mjackson/.rvm/scripts/rvm
sk
nano ~/.bash_profile
type rvm | head -1
rvm | head -1
rvm install 1.9.2
sk
cd ~/
ll
cd cita/
ll
cd bash/
git init
git add .
git remote add origin https://github.com/meshachjackson/Bash.git
git pull origin master
git add .
gma "initial commit"
git push origin master
ll
